### ISSUE TITLE
[Thunderbird] Feature Request: Open Message by Clicking on the Whole Notification

### ISSUE THREAD

**Issue by pretodor** [mkiol/GNotifier#123]
Instead of having a separate button for opening the message, we should be able to do this by clicking on the whole notification. You can make an analogy with the way Spotify handles notifications.

(By the way, I'm running Linux Mint 17.2 Cinnamon)

**Comment by mkiol** [comment]
Thanks for the request. Good news is that I know how to fix it. 

I missed that during my tests because GNOME an KDE  always show buttons if notification is clickable. In case Cinnamon, when some action is tagged as "default", button is not shown and action is triggered by clicking on whole notification.

**Comment by pretodor** [comment]
That's excellent news, @mkiol !

I'm looking forward to your upcoming commits.

**Comment by mkiol** [comment]
Fix is in the latest "beta" XPI - [gnotifier-1.9.8-pre3.xpi](https://github.com/mkiol/GNotifier/tree/master/xpi).  It is not signed package.

Tested on Mint 18 Cinnamon.

**Comment by ghost** [comment]
Just tested this out. It works great! Thanks for your work. I'm closing this issue.

**Comment by mkiol** [comment]
I'm glad I could help. Thanks for testing.
