### ISSUE TITLE
&nbsp; character is not converted to space

### ISSUE THREAD

**Issue by petr-nehez** [mkiol/GNotifier#185]
When there is ```&nbsp;``` character in a body then it is not converted into space.

![image](https://user-images.githubusercontent.com/1265990/29804990-0df39be8-8c87-11e7-9517-ce5ba21e755a.png)

![image](https://user-images.githubusercontent.com/1265990/29804952-b358f4c6-8c86-11e7-8761-a12589fd3cd4.png)

Kubuntu 17.04 & Thunderbird 52.2.1

**Comment by mkiol** [comment]
Yes, it looks ugly because notification server accepts only small subset of HTML. According this [spec](https://developer.gnome.org/notification-spec/#markup) only following tags are mandatory to support on server side: \<b>, \<i>, \<u>, \<a>, \<img> and nothing more. 

To make it more elegant, Gnotifier should do some additional processing and discard every unsupported HTML symbols before sending data to notification server. It is possible but not so easy to implement. 

This issue is related to #24.

**Comment by petr-nehez** [comment]
Just a note - I am using KDE so I am not sure if GNOME link @mkiol mentioned above can be applied on KDE as well.

**Comment by mkiol** [comment]
I think it applies to all notification servers. I've tested KDE server and for sure it supports only "\<b>, \<i>, \<u>, \<a>, \<img>" :-(

**Comment by mkiol** [comment]
The Issue has been fixed in the latest dev xpi.
