### ISSUE TITLE
GNotifier not working in new Firefox 57

### ISSUE THREAD

**Issue by itcrowd72** [mkiol/GNotifier#197]
GNotifier not working in new Firefox 57. Firefox disable it.

**Comment by mkiol** [comment]
GNotifier is not a WebExtension, so it was disabled in FF 57. Unfortunately due to few constrains - see #162 - it is not possible to "fix" it to be compatible with the newest FF release.

I've decided to continue development only focusing on Thunderbird.

**Comment by itcrowd72** [comment]
It's a pity! :(

**Comment by tooomm** [comment]
Just curious @mkiol.
What kind of `dll` files are needed to make this work on windows? What do they provide?

**Comment by mkiol** [comment]
@tooomm 

DLL is [here](https://github.com/mkiol/GNotifier/tree/master/source/resources/gnotifier/data) and the sources are [here](https://github.com/mkiol/GNotifier/tree/master/win8_shim). 

Unlike Linux, on Windows GNotifier interacts with OS notification API not directly (using javascript code) but via "adaptor" implemented in C++ and provided as a DLL. GNotifier calls relatively simple js function: `notify (iconURL, title, text, notifier, closeHandler, clickHandler)` and DLL transforms it to something understandable by Windows API.

This crafty implementation was entirely done by @kabili207.

**Comment by tooomm** [comment]
@mkiol Are you sure you still rely on that if you would start using WebExtensions?
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Notifications
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/notifications

**Comment by mkiol** [comment]
@tooomm Unfortunately it is not so simple. Yes, there is WebExtension API for triggering notifications but this API doesn't produce "native" integration on Windows. When you call `notifications.create()` FF will show ugly HTML thing instead nice action center bubble.

To sum up, there are following blockers for re-implementation GNotifier as a WebExtension:
1. no DLLs and [js-ctypes API](https://developer.mozilla.org/en-US/docs/Mozilla/js-ctypes) -> add-on is not able to interact with native binaries in the OS*
2. no API that allows add-on to change the default notification engine in the browser

*) Actually there is a possibility to use [Native messaging API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging). It is ugly solution because it requires user to install EXE file in the system. This EXE file will not be distributed with the add-on. I really dislike this approach.

**Comment by tooomm** [comment]
Thanks for investigating further.

So we are dependent on mozilla to support native notification systems at one point...
@kabili207 posted the [tracking issue at mozilla for windows toast notifications](https://bugzilla.mozilla.org/show_bug.cgi?id=1155505) here: https://github.com/mkiol/GNotifier/issues/162#issuecomment-345523359

No idea about other operating systems. :/

**Comment by ViBE-HU** [comment]
feels bad. this is one of my daily driver extensions.

**Comment by Forage** [comment]
Who cares about Windows support? We only need it to work in Firefox for Linux! ;)

**Comment by RaEyE** [comment]
@mkiol 
Thank you for your elaborate answer. Thats really nice to know.
urrently I'm using Thunderbird Beta (58b2), would you say, there is a possibility to run GNotifier with that release? I'm asking since you also published a release for Beta 56.
